Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'libraries/default.rb'
    - 'recipes/yum_pgdg_postgresql.rb'

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'libraries/default.rb'

Lint/UnreachableCode:
  Exclude:
    - 'libraries/default.rb'

# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'libraries/default.rb'

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Style/MethodName:
  Enabled: false

Style/MultilineBlockChain:
  Exclude:
    - 'recipes/server.rb'

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
# SupportedStyles: skip_modifier_ifs, always
Style/Next:
  Exclude:
    - 'libraries/default.rb'

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Exclude:
    - 'test/unit/server_spec.rb'

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: snake_case, camelCase
Style/VariableName:
  Enabled: false
